### ISSUE TITLE
libpepflashplayer.so not found in /usr/lib/pepperflashplugin-nonfree

### ISSUE THREAD

**Issue by hiagohubert** [baptistedonaux/deezer-desktop-linux#3]
I solved this using the "locate" command and copied the file to the correct place

`locate libpepflashplayer.so`

**Comment by baptistedonaux** [comment]
@hiagohubert Thank you for your feedback.

I must work to propose a feature which setup ```libpepflashplayer.so``` at the good location.

**Comment by hiagohubert** [comment]
Thank you for develop deezer for linux :grinning:

**Comment by mrgustavosantiago** [comment]
I have problems to execute a music on Deezer, i make a copy of the file to a folder but don't work :(

**Comment by baptistedonaux** [comment]
Currently, application uses the binary at this location.
```
/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
```

**Comment by deyvisonrocha** [comment]
@baptistedonaux thanks for this.

I use a link to resolve my problem:

```
mkdir -p /usr/lib/pepperflashplugin-nonfree/
sudo sudo ln -s /home/<myuser>/.config/google-chrome/PepperFlash/25.0.0.127/libpepflashplayer.so /usr/lib/pepperflashplugin-nonfree/
```

**Comment by baptistedonaux** [comment]
I would like develop a feature to embed libpepflashpalyer.so and extract it when no library is found.

**Comment by mrgustavosantiago** [comment]
@deyvisonrocha, thanks a lot!

it's working :D

**Comment by ledeanri** [comment]
How to enable flashplugin? The app run with browser core but without flashplugin active.

**Comment by marcelorsoares** [comment]
@ledeanri You must have installed the plugin **pepperflashplugin-nonfree**.
If you are using Ubuntu try install using this command in the terminal:
`sudo apt-get install pepperflashplugin-nonfree`
Worked for me on Ubuntu 17.04

**Comment by ledeanri** [comment]
@marcelorsoares Maybe I was not very clear, look at my error: http://oi63.tinypic.com/ouozub.jpg

**Comment by marcelorsoares** [comment]
@ledeanri It happened the same with me. I went to see the source code and I saw that in the **main.js** file on the **app** folder it references the **libpepflashplayer** library. When I search for the file in the `/usr/lib/pepperflashplugin-nonfree/` path I did not find. I installed the library and tried to run again and then it worked. 
Did you installed the library and the error continues?

**Comment by ledeanri** [comment]
@marcelorsoares yes i install the lib and the error continue.

**Comment by marcelorsoares** [comment]
@ledeanri Did you check if the folder `/usr/lib/pepperflahsplugin-nonfree/` exists?

**Comment by ledeanri** [comment]
@marcelorsoares yep, this folder exists

**Comment by baptistedonaux** [comment]
This project is no longer maintained. You can use [MellowPlayer](https://colinduquesnoy.github.io/MellowPlayer/).
